/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiplexsystem;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import java.util.*;
import java.text.*;

/**
 *
 * @author Smit
 */


public class MovieData extends javax.swing.JFrame {

    /**
     * Creates new form Shows
     */
    
    public static String date2;
    public static String multiplexName;
    public static String[] mid = new String[100];
    public static String[] movieName = new String[100];
    public static Integer[] year = new Integer[100];
    public static String[] genre = new String[100];
    public static String[] certi = new String[100];
    public static Integer[] duration = new Integer[100];
    public static Float[] rating = new Float[100];
    public static String selectedId;
    public static String selectedName;
    
       
    ImageIcon icon;
    Image mulImage;
    MultiplexData1 MD1;
    public MovieData() {
        initComponents();
        multiplexName=MultiplexData1.cinemaName;
        getMovieList();
        mName.setVisible(false);
        mGenre.setVisible(false);
        mYear.setVisible(false);
        mCerti.setVisible(false);
        mDuration.setVisible(false);
        mRating.setVisible(false);
        lDuration.setVisible(false);
        lRating.setVisible(false);
        lAge.setVisible(false);
        
        ShowBox.setSelectedIndex(0);
        displayMovieData();
    }
     public MovieData(MultiplexData1 md1) {
        initComponents();
        multiplexName=MultiplexData1.cinemaName;
        getMovieList();
        mName.setVisible(false);
        mGenre.setVisible(false);
        mYear.setVisible(false);
        mCerti.setVisible(false);
        mDuration.setVisible(false);
        mRating.setVisible(false);
        lDuration.setVisible(false);
        lRating.setVisible(false);
        lAge.setVisible(false);
        MD1=md1;
        ShowBox.setSelectedIndex(0);
        displayMovieData();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        ShowBox = new javax.swing.JComboBox<>();
        movieLabel = new javax.swing.JLabel();
        getShowButton = new javax.swing.JButton();
        mCerti = new javax.swing.JLabel();
        mName = new javax.swing.JLabel();
        mDuration = new javax.swing.JLabel();
        mGenre = new javax.swing.JLabel();
        mYear = new javax.swing.JLabel();
        lDuration = new javax.swing.JLabel();
        lRating = new javax.swing.JLabel();
        mRating = new javax.swing.JLabel();
        lAge = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        imageLabel1 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();

        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ShowBox.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ShowBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ShowBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ShowBoxItemStateChanged(evt);
            }
        });
        ShowBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBoxActionPerformed(evt);
            }
        });

        movieLabel.setFont(new java.awt.Font("Sitka Small", 0, 24)); // NOI18N
        movieLabel.setText("Select Movie:");

        getShowButton.setFont(movieLabel.getFont());
        getShowButton.setText("Get Shows");
        getShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getShowButtonActionPerformed(evt);
            }
        });

        mCerti.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        mCerti.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mCerti.setText("jLabel1");

        mName.setFont(new java.awt.Font("Sitka Small", 3, 44)); // NOI18N
        mName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mName.setText("jLabel1");

        mDuration.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        mDuration.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mDuration.setText("jLabel1");

        mGenre.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        mGenre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mGenre.setText("jLabel1");

        mYear.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        mYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mYear.setText("jLabel1");

        lDuration.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        lDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDuration.setText("Duration:");

        lRating.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        lRating.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lRating.setText("Rating:");

        mRating.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        mRating.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mRating.setText("jLabel1");

        lAge.setFont(new java.awt.Font("Sitka Small", 2, 20)); // NOI18N
        lAge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAge.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Select Date:");

        date1.setFocusTraversalPolicyProvider(true);
        date1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        error.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(getShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(movieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ShowBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(imageLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mYear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(mCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lRating, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(mDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mGenre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(83, 83, 83))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lAge, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(mRating, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(101, 101, 101))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mYear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mCerti, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lAge, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lRating, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(error, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imageLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movieLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowBox, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(date1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(getShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getShowButtonActionPerformed
        // TODO add your handling code here:
        selectedId = mid[ShowBox.getSelectedIndex()];
        selectedName = ShowBox.getSelectedItem().toString();
        
        //date1.setDateFormatString("yyyy-mm-dd");
        try{
        
       Date  h=date1.getDate();
        
       
        long millis=System.currentTimeMillis()+5000;
        Date date=new Date(millis);
        
        if(date1.getDate().compareTo(date)<0){
            
            error.setText("INVALID DATE");
            return;
        
        }
        
        
        
        SimpleDateFormat df=new SimpleDateFormat("dd-MMM-yyyy");
        
        date2=df.format(h);
        
        System.out.println(date2);
        
        
        
        
        
        ShowTime s = new ShowTime(this);
        this.setVisible(false);
        s.setVisible(true);
        
        }
        
        catch(Exception e){
        
           error.setText("no date Selected");
           return;
        }
        
    }//GEN-LAST:event_getShowButtonActionPerformed

    private void ShowBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ShowBoxItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ShowBoxItemStateChanged

    private void ShowBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBoxActionPerformed
        // TODO add your handling code here:
        displayMovieData();
    }//GEN-LAST:event_ShowBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MD1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieData().setVisible(true);
            }
        });
    }
    
    
    public void getMovieList(){
           
           ShowBox.removeAllItems();
           Connection con=Authentication.CustomerConn();
           try{  
            int p=0;
            Statement stmt=con.createStatement(); 
            ResultSet rs=stmt.executeQuery("select movie.name,movie.year,movie.runtime,movie.genre,movie.rating,movie.certification,movie.imdb_id from movie inner join movmul on movie.imdb_id=movmul.imdb_id and movmul.mname=\'"+multiplexName+"\' and movie.imdb_id in (select s.imdb_id from shows s where s.mname=\'"+multiplexName+"\');");  
        
           while(rs.next()){
            movieName[p]=rs.getString(1);
            year[p]=rs.getInt(2);
            duration[p]=rs.getInt(3);
            genre[p]=rs.getString(4);
            rating[p]=rs.getFloat(5);
            certi[p]=rs.getString(6);
            mid[p]=rs.getString(7);
                       
           int x=1;
           
           for(int i=0;i<ShowBox.getItemCount();i++){
           
            if(ShowBox.getItemAt(i).toString().equals(movieName[p]))
                x=0;
           }
           if(x==1)
               ShowBox.addItem(movieName[p]);
           p++;
        }  
 
             con.close();
                   
        }
           catch(Exception e){
            System.out.println(e);
           }
           
        icon = new ImageIcon("C:\\Users\\Smit\\Pictures\\multiplex\\"+multiplexName+".jpg");
        mulImage = icon.getImage().getScaledInstance(350,400,Image.SCALE_DEFAULT);
        imageLabel.setIcon(new ImageIcon(mulImage));
    }
    
    public void displayMovieData(){
        
            mName.setVisible(true);
            mGenre.setVisible(true);
            mCerti.setVisible(true);
            mYear.setVisible(true);
            mDuration.setVisible(true);
            mRating.setVisible(true);
            lDuration.setVisible(true);
            lRating.setVisible(true);
            lAge.setVisible(true);
           
           int i = ShowBox.getSelectedIndex();
           int age=18;
           try{  
        
               mName.setText(movieName[i]);
               mYear.setText(year[i]+"");
               mGenre.setText(genre[i]);
               mCerti.setText(certi[i]);
               mDuration.setText(duration[i] + " mins");
               mRating.setText(rating[i] + " /10");
               icon = new ImageIcon("C:\\Users\\Akhil Agrawal\\Pictures\\Movie\\"+mid[i]+".jpg");
                mulImage = icon.getImage().getScaledInstance(350,400,Image.SCALE_DEFAULT);
                imageLabel1.setIcon(new ImageIcon(mulImage));
        
               try{
                   Connection con=Authentication.CustomerConn();
                   Statement stmt=con.createStatement(); 
                   ResultSet rs=stmt.executeQuery("Select age from mcertification where certification = \'"+certi[i]+"\';");
                   
                   while(rs.next())
                    age=rs.getInt(1);
                   lAge.setText(age+"+");
               }
               catch(Exception e){
                   
               }
                   
           }
           catch(Exception e){
            System.out.println(e);
           }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ShowBox;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JLabel error;
    private javax.swing.JButton getShowButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel imageLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAge;
    private javax.swing.JLabel lDuration;
    private javax.swing.JLabel lRating;
    private javax.swing.JLabel mCerti;
    private javax.swing.JLabel mDuration;
    private javax.swing.JLabel mGenre;
    private javax.swing.JLabel mName;
    private javax.swing.JLabel mRating;
    private javax.swing.JLabel mYear;
    private javax.swing.JLabel movieLabel;
    // End of variables declaration//GEN-END:variables
}
